---
- hosts: virtualbox
  become: yes

  roles:
    - { role: ius, when: lingvo_dev is defined }
    - { role: python35, when: lingvo_dev is defined }

  tasks:
    - name: Install python2 pip
      yum: name={{ item }} state=present
      with_items:
        - python2-pip
        - python-virtualenv
      when: lingvo_dev is defined
      tags: lingvo

    - name: Install python2 packages with pip
      pip: name={{ item }} state=present
      with_items:
        - NumPy
        - SciPy
        - Pandas
        - scikit-learn
      when: lingvo_dev is defined
      tags: lingvo

    - name: Install python3 packages with pip
      pip: name={{ item }} state=present executable=pip3.5
      with_items:
        - NumPy
        - SciPy
        - Pandas
        - scikit-learn
      when: lingvo_dev is defined
      tags: lingvo
