---

- name: Load correct ius repo url inside a variable
  include_vars: el{{ ansible_distribution_major_version }}.yml

- name: Install ius repo.
  yum:
    name: "{{ ius_repo_url }}"
    state: present
  # register: result
  # until: '"failed" not in result'
  # retries: 5
  # delay: 10

- name: Import ius GPG key.
  rpm_key:
    key: "{{ ius_repo_gpg_key_path }}"
    state: present
