---

# SSH Host Keys
#- name: Generate /etc/ssh/ RSA host key
#  command : ssh-keygen -q -t rsa -f /etc/ssh/ssh_host_rsa_key -C "" -N ""
#  creates: /etc/ssh/ssh_host_rsa_key
#
#- name: Generate /etc/ssh/ DSA host key
#  command : ssh-keygen -q -t dsa -f /etc/ssh/ssh_host_dsa_key -C "" -N ""
#  creates: /etc/ssh/ssh_host_dsa_key
#
#- name: Generate /etc/ssh/ ECDSA host key
#  command : ssh-keygen -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -C "" -N ""
#  creates: /etc/ssh/ssh_host_ecdsa_key
#
#- name: Generate SSH key for root
#  shell: ssh-keygen -q -b 2048 -t rsa -f /root/.ssh/id_rsa -C "" -N ""
#  args:
#    creates: /root/.ssh/id_rsa

# !!!перегенирируется ключ даже если он уже присутствует!!!
#- name: Generate SSH key for root (This will not overwrite an existing SSH key.)
#  user:
#    name: root
#    generate_ssh_key: yes

- name: Firewalld stop
  service: name=firewalld enabled=no state=stopped

- name: Disable SELinux
  lineinfile: dest=/etc/selinux/config state=present regexp='^SELINUX=.*$' line='SELINUX=disabled'

- name: Set Timezone to {{ timezone }}
  file: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link force=yes

- name: Epel repository
  yum: 
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: ELRepo repository
  yum: 
    name: https://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
    state: present

#- name: MLG Internal Repo
#  yum: 
#    name: http://10.10.28.99/Packages/mlg-release-1.0-1.el7.noarch.rpm
#    state: present

- name: Install essential software
  yum: name={{ item }} state=latest
  tags: software
  with_items:
   - atop
   - bind-utils
   - bzip2
   - curl
   - gcc
   - gdb
   - git
   - htop
   - iptraf
   - mc
   - mtr
   - mytop
   - net-tools
   - nethogs
   - ngrep
   - ntpdate
   - openssl-devel
   - psmisc
   - rsync
   - screen
   - sysstat
   - tcpdump
   - unzip
   - vim
   - wget
   - zip

#- name: Mail sender
