---
 - name: Userparameter for vz confs host
   register: copyconfig
   template: src=userparameter_vhosts.conf dest={{ zbx_include_dir }}/ owner=zabbix group=zabbix mode=0640
   notify:
    - zabbix-agent restart


 - name: Copy bin check_vhosts.sh
   when: copyconfig | success
   copy: src=check_vhost.sh dest={{ zbx_bin_dir }}/check_vhost.sh owner=root group=root mode=0755
   register: copy_checkvhosts
   notify:
    - zabbix-agent restart

 - name: Copy bin get_all_vhosts.sh
   when: copy_checkvhosts | success
   copy: src=get_all_vhosts.sh dest={{ zbx_bin_dir }}/get_all_vhosts.sh owner=root group=root mode=0755
   register: copy_getallvhosts
   notify:
    - zabbix-agent restart
