---
 - name: Add repo for Zabbix
   when: ansible_os_family == 'Debian'
   apt_repository: repo='deb http://repo.zabbix.com/zabbix/2.4/debian wheezy main' state=present
   register: install_repo

 - name: Add key
   when: ansible_os_family == 'Debian'
   apt_key: id=79EA5ED4
      url=http://repo.zabbix.com/zabbix-official-repo.key

 - name: Install Zabbix agent
   apt: update_cache=yes name=zabbix-agent
   when: install_repo | success
   register: zabbixagentinstalled
   notify:
    - zabbix-agent start

 - name: Create dirs ZBX include
   register: createdirinc
   when: zabbixagentinstalled | success
   file: path={{ zbx_include_dir }} state=directory owner=zabbix group=zabbix

 - name: Create dirs ZBX bin
   register: createdirbin
   when: createdirinc | success
   file: path={{ zbx_bin_dir }} state=directory owner=zabbix group=zabbix

 - name: Configure Zabbix agent
   when: zabbixagentinstalled | success
   register: restartzabbix
   template: src=zabbix_agentd.conf dest={{ zbx_config }}
   notify:
    - zabbix-agent restart

 - name: Configure SUDO for zabbix
   when: restartzabbix | success
   copy: src=sudo_zabbix dest={{ sudo_dird }}/zabbix owner=root group=root mode=0440
